"""Convert HP Omen devicelist json to a id struct"""
import json

def gen_device_list(devices):
  print("static const struct dmi_system_id omen_quirks[] __initconst = {")
  for dev in devices:
    for board in dev["ProductNum"]:
      print("""  {{
    .callback = dmi_matched,
    .ident = "{}",
    .matches = {{
      DMI_EXACT_MATCH(DMI_BOARD_NAME, "{}"),
      }},
    .driver_data = {},
  }},""".format(dev["DisplayName"], board, dev["BackgroundFeature"]))
  print("  {}\n};\n")

if __name__ == "__main__":
  devicelist = []

  with open("omen_cs/HP.Omen.DeviceLib.JSON.DeviceList.json", "r") as f:
    devicelist = json.load(f)
    print("// ident.h")
    print("// generated by gen_ident.py from HP.Omen.DeviceLib.JSON.DeviceList.json\n")
    gen_device_list(devicelist)

